apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-own-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-own-app
  template:
    metadata:
      labels:
        app: my-own-app
    spec:
      containers:
      - name: my-own-app
        image: evanhoof134/my-own-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"