apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-own-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-own-app
  template:
    metadata:
      labels:
        app: my-own-app
    spec:
      containers:
      - name: my-own-app
        image: my-own-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-own-app-service
  namespace: my-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-own-app
